### PR TITLE
BPM controller changes

### PR DESCRIPTION
**Pull request by adb-xkc85723**
I put in a couple of extra functions to the Python DLL to let the user see if the BPM data was being monitored. I'm pretty sure it works fine.

Alex

### CODE REVIEW

**Comment by mothyjohn** [comment]
We dont use the string 'Direc' in  the velaINJBeamPositionMonitorController.cpp constructor anymore

**Comment by adb-xkc85723** [comment]
Bugger, I thought I’d taken that out. Could you remove it? The controller should still work anyway.

Alex

**Comment by mothyjohn** [comment]
okay

**Comment by mothyjohn** [comment]
seem i can merge it because there are some conflicts not sure where they are though... hmm

**Comment by mothyjohn** [comment]
i can't merge that it...

**Pull request closed without merging**
